# Generated by Django 5.2.3 on 2025-06-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
