# Generated by Django 5.2.3 on 2025-06-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.ManyToManyField(blank=True, to='auctions.category'),
        ),
    ]
