# Generated by Django 5.2.3 on 2025-06-24 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionlistings_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='category',
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.category'),
        ),
    ]
