# Generated by Django 5.2.3 on 2025-06-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auctionlistings_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
