# Generated by Django 5.2.3 on 2025-06-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlistings_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, to='auctions.auctionlistings'),
        ),
    ]
